name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: busted
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4

      - name: build
        run: |
          luarocks install busted
          luarocks install --only-deps luadns-templates-dev-1.rockspec

      - name: test
        run: |
          luarocks test
